### ISSUE TITLE
Things to add

### ISSUE THREAD

**Issue by zkevinbai** [zkevinbai/Alexandria#57]
### Show

- [x] close out of modal when opened

- [x] render add book modal for when user logged in 

### Styling

- [ ] flush out styling of book show and books index

### General Things to Add

- [x] integrate analytics of books in user library

- [x] integrate suggestions to users based on books in user library

**Comment by chickey96** [comment]
- [x] clear text on search bar

- [x] clear state on logout

- [x] title for index page?

- [ ] fix login bug(think I fixed part of the problem, it wasn't recognizing state.errors === {} as true when it should have been)

- [x] make errors on signup visible (I didn't see a problem with these, but I fixed the scrolling issues on the session form -Sam) 


- [x] fix modal overlay scroll

**Comment by chickey96** [comment]
- [x] fix graph font

- [x] fix logout outline when active

- [x] fix bug when switching users, shelf isn't rendered

- [ ] fix back button

- [ ] make splash page resizable

- [x] fix size of default book image, it's really big
